# PRH Demo

In [1]:
import phimaker as pm
import oat_python as oat
import plot as pltter
import numpy as np
import prh as prh
import plotly.graph_objects as go
from IPython.display import display, HTML

In [2]:
# to view pandas DFs for debugging
def display_scrollable(df, height=300):
    html = df.to_html()
    html = f'<div style="max-height:{height}px; overflow:auto;">{html}</div>'
    display(HTML(html))

## Simple Demo 

The code chunks below exemplify how to use all of the functions implemented here.

In [3]:
# PARAMETERS TO GENERATE DATA
r = 0.25
dx = 0.25
dy = 0.25
epsilon = np.sqrt(2 * dx**2) 
blob_radius = epsilon + 0.0000001

# GENERATE THE DATA 
coo_grid, dissimilarity_matrix_full_space_grid, dissimilarity_matrix_subspace_grid, fig_grid, subcloud_indices_grid, blob_membership_grid = pltter.create_paint_palette(r, dx, dy, epsilon, blob_radius, [0], False, "Demo Paint Palette")

# SHOW THE RESULT
fig_grid.show()

In [4]:
alg_manager = prh.prh(coo_grid, np.column_stack([subcloud_indices_grid, np.full(4, 0.0)]), 1, epsilon + 0.0000001)

In [5]:
# get simplices sorted by subcomplex order
simplices_subcomplex_df = alg_manager.simplices_subcomplex_order_data_frame()
display_scrollable(simplices_subcomplex_df)

In [6]:
# get simplices sorted by full complex order
simplices_df = alg_manager.simplices_full_complex_order_data_frame()
display_scrollable(simplices_df)

In [7]:
# check the chains along the columns of the target COMB
target_df = alg_manager.target_comb_data_frame()
display_scrollable(target_df)

In [8]:
# check the chains along the columns of the source COMB
source_df = alg_manager.source_comb_data_frame()
display_scrollable(source_df)

In [9]:
# check the chains along the rows of the relative boundary matrix  
boundary_df = alg_manager.relative_boundary_matrix_data_frame()
display_scrollable(boundary_df)

In [10]:
# check the relative cycle basis 
cycle_df = alg_manager.relative_cycle_basis()
display_scrollable(cycle_df) 
print(cycle_df[cycle_df['birth filtration'] != np.inf]['dimension'].value_counts())
# ==========
# uncomment/edit the chunk below to plot chains
# use the `integer_idx` of the `cycle_df` here to get chains from the `source_df` above
# make sure to update the dimension accordingly
# ==========
# fig_cycle_grid = go.Figure(fig_grid.data)
# edges = [pair[0] for pair in source_df["chain"][0]]
# pltter.plot_chain(edges, 0, coo_grid, fig_cycle_grid, "cycle", "Relative Cycle", "purple")
# fig_cycle_grid.update_layout(title=dict(text="Plotted Relative Cycle"), template="plotly_dark", height=800, width=850).show()

dimension
1    15
0     9
2     7
Name: count, dtype: int64

In [11]:
# check the relative boundary basis
boundary_df =alg_manager.relative_boundary_basis()
display_scrollable(boundary_df)
print(boundary_df[boundary_df['birth filtration'] != np.inf]['dimension'].value_counts())
# ==========
# uncomment/edit the chunk below to plot chains
# use the `integer_idx` of the `boundary_df` here to get chains from the `target_df` above
# make sure to update the dimension accordingly
# ==========
# fig_boundary_grid = go.Figure(fig_grid.data)
# edges = [pair[0] for pair in target_df["chain"][26]]
# pltter.plot_chain(edges, 1, coo_grid, fig_boundary_grid, "boundary", "Relative Boundary", "purple")
# fig_boundary_grid.update_layout(title=dict(text="Plotted Relative Boundary"), template="plotly_dark", height=800, width=850).show()

dimension
1    15
0     9
2     4
Name: count, dtype: int64

In [12]:
# compute PRH
homology_df = alg_manager.main_algorithm()
display_scrollable(homology_df)
print(homology_df['dimension'].value_counts())

dimension
0    5
1    3
Name: count, dtype: int64

In [13]:
fig_cycle_grid = go.Figure(fig_grid.data)
edges = [pair[0] for pair in homology_df["chain"][7]]
pltter.plot_chain(edges, 1, coo_grid, fig_cycle_grid, "cycle", "Cycle", "purple")
fig_cycle_grid.update_layout(title=dict(text="Plotted Relative Cycle"), template="plotly_dark", height=800, width=850).show()

## Compatibility with Two Filtrations 

Now make the example above a bit larger. In addition, we customize the subcomplex filtration and compute representatives for essential relative homology classes.

In [14]:
# PARAMETERS TO GENERATE DATA
r = 0.5
dx = 0.25
dy = 0.25
epsilon = np.sqrt(2 * dx**2) 
blob_radius = epsilon + 0.0000001

# GENERATE THE DATA 
coo_grid, dissimilarity_matrix_full_space_grid, dissimilarity_matrix_subspace_grid, fig_grid, subcloud_indices_grid, blob_membership_grid = pltter.create_paint_palette(r, dx, dy, epsilon, blob_radius, [0, 20, 24], False, "Demo Paint Palette")

# SHOW THE RESULT
fig_grid.show()

In [15]:
alg_manager = prh.prh(coo_grid, np.column_stack([subcloud_indices_grid, np.full(12, 0.0)]), 1, epsilon + 0.0000001)
homology_df = alg_manager.main_algorithm()
display_scrollable(homology_df)
print(homology_df['dimension'].value_counts())

dimension
1    15
0    13
Name: count, dtype: int64

To exemplify that this output is correct, notice that it is simple to count how many classes we have in the absolute homology case. There are 25 0-homology classes corresponding to the 25 points, and there are 16 1-homology classes corresponding to the partition of the grid into 16 sqaures. We lose 12 0-homology classes in the relative homology case. On the other hand, we lose three 1-homology classes in the relative homology case, but gain back an additional two since the subcomplex is given by three disjoint pieces. The generators for these classes are plotted below, together with a barcode.

In [16]:
fig_cycle_grid = go.Figure(fig_grid.data)
edges_1 = [pair[0] for pair in homology_df["chain"][17]]
edges_2 = [pair[0] for pair in homology_df["chain"][22]]
pltter.plot_chain(edges_1, 1, coo_grid, fig_cycle_grid, "cycle-1", "Relative Cycle", "purple")
pltter.plot_chain(edges_2, 1, coo_grid, fig_cycle_grid, "cycle-2", "Relative Cycle", "orange")
fig_cycle_grid.update_layout(title=dict(text="Plotted Relative Cycle"), template="plotly_dark", height=800, width=850).show()

In [17]:
barcode = pltter.plot_barcode( 
    homology_df["birth"].values, 
    homology_df["death"].values, 
    homology_df["dimension"].values, 
    "Example Barcode"              
)
barcode.show()

Now let's customize the subcomplex filtration. For example, we will alter one cluster of points such that we gain an additional four 0-homology classes which do not persist as long as the others. We can also alter another cluster such that we (1) gain back another four 0-homology classes, (2) gain back an additional 1-homology class which does not persist as long as the others and (3) delay the birth of one of the essential classes.

In [18]:
custom_diameters = [0,0,0,0,0.125,0.125,0.3,0.3,0.125,0.125,0.3,0.3]
custom_data = np.column_stack([subcloud_indices_grid, custom_diameters])
alg_manager = prh.prh(coo_grid, custom_data, 1, epsilon + 0.0000001)
custom_homology_df = alg_manager.main_algorithm()
# show the data frame 
display_scrollable(custom_homology_df)
print(custom_homology_df['dimension'].value_counts())
# show the barcode
barcode = pltter.plot_barcode( 
    custom_homology_df["birth"].values, 
    custom_homology_df["death"].values, 
    custom_homology_df["dimension"].values,
    "Example Barcode",    
)
barcode.show()

dimension
0    21
1    16
Name: count, dtype: int64

In [19]:
fig_cycle_grid = go.Figure(fig_grid.data)
edges_1 = [pair[0] for pair in custom_homology_df["chain"][36]]
edges_2 = [pair[0] for pair in custom_homology_df["chain"][35]]
pltter.plot_chain(edges_1, 1, coo_grid, fig_cycle_grid, "cycle-1", "Relative Cycle", "purple")
pltter.plot_chain(edges_2, 1, coo_grid, fig_cycle_grid, "cycle-2", "Absolute Cycle", "orange")
fig_cycle_grid.update_layout(title=dict(text="Plotted Relative Cycle"), template="plotly_dark", height=800, width=850).show()

## A Larger Example

In [20]:
r = 0.5
dx = 0.165
dy = 0.165
epsilon = 1.17 * np.sqrt(2 * dx**2) 
blob_radius = 0.25
coo, dissimilarity_matrix_full_space, dissimilarity_matrix_subspace, fig, subcloud_indices, blob_membership = pltter.create_paint_palette(r, dx, dy, epsilon, blob_radius, None, True, "Demo Paint Palette")
fig.show()

In [21]:
alg_manager = prh.prh(coo, np.column_stack([subcloud_indices, np.full(len(subcloud_indices), 0.0)]), 1, epsilon + 0.0000001)
homology_df = alg_manager.main_algorithm()
display_scrollable(homology_df)
print(homology_df['dimension'].value_counts())

dimension
0    49
1    24
Name: count, dtype: int64

In [22]:
# # UNCOMMENT TO PLOT CYCLE REPRESENTATIVES
# fig_cycle = go.Figure(fig.data)
# edges_1 = [pair[0] for pair in homology_df["chain"][52]]
# edges_2 = [pair[0] for pair in homology_df["chain"][71]]
# edges_3 = [pair[0] for pair in homology_df["chain"][70]]
# pltter.plot_chain(edges_1, 1, coo, fig_cycle, "cycle", "Cycle", "purple")
# pltter.plot_chain(edges_2, 1, coo, fig_cycle, "cycle", "Cycle", "yellow")
# pltter.plot_chain(edges_3, 1, coo, fig_cycle, "cycle", "Cycle", "orange")
# fig_cycle.update_layout(title=dict(text="Essential Cycles"), template="plotly_dark", height=800, width=850).show()

In [23]:
barcode = pltter.plot_barcode( 
    homology_df["birth"].values, 
    homology_df["death"].values, 
    homology_df["dimension"].values,
    "Example Barcode",    
)
barcode.show()